version: "3"

services:
  mysqldb:
    image: mysql:8.0.33
    container_name: mysqldb
    command: 
        --bind-address=0.0.0.0
    restart: always
    #env_file: ./.env
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10  

  app:
    image: 'docker-spring-boot-server:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8881:8881" # expose local port
    depends_on:
      mysqldb:
        condition: service_healthy

volumes:
  mysql-data:
